language: java
sudo: false # faster builds

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
jdk:
  - oraclejdk8
  - oraclejdk9

services:
  - docker
cache:
  directories:
  - "$HOME/.cache"

script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)